name: Jest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm test

name: Build and Deploy

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: wanjun-ecr
  ECS_CLUSTER: wanjun-ecs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
    - name: Build and push Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
    - name: Deploy to Amazon ECS Fargate
      uses: aws-actions/amazon-ecs-deploy-task@v1
      with:
        cluster: ${{ env.ECS_CLUSTER }}
        task_definition: wanjun-task
        service: wanjun-ecsservice
        container_name: wanjun-ecscontainer
        image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
