name: Jest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm test

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: wanjun-ecr
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build and Push Docker Image to ECR
        id: build-and-push
        env:
          ECR_REGISTRY: wanjun-ecr
          IMAGE_NAME: wanjun-dockerimage
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  deploy-to-ecs-fargate:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: wanjun-ecr
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Deploy to ECS Fargate
        uses: aws-actions/amazon-ecs-deploy@v1
        with:
          cluster: <your-ecs-cluster>
          service: <your-ecs-service>
          image: wanjun-ecr/wanjun-dockerimage:${{ github.sha }}
          aws-region: ap-northeast-1